version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: video-streamer-web
    restart: unless-stopped
    ports:
      - 80:8080
      - 1606:1606
    volumes:
      - ./:/app