version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: showveo-web
    restart: unless-stopped
    ports:
      - 12001:8080
    volumes:
      - ./:/app